language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

script:
  # test embedded tomcat
  - ./gradlew -u -i -S tomcatInstall
  - ./gradlew -u -i -S tomcatStart
  - ./gradlew -u -i -S tomcatStop
  # test HSQL
  - ./gradlew -u -i -S hsqlStart
  - ./gradlew -u -i -S dataInit
  - ./gradlew -u -i -S hsqlStop

cache:
  directories:
    - .gradle
    - $HOME/.gradle/
