language: java
jdk: oraclejdk8
dist: trusty
sudo: false

script:
  # test embedded tomcat
  - ./gradlew -u -i -S tomcatInstall
  - ./gradlew -u -i -S tomcatStart
  - ./gradlew -u -i -S tomcatStop
  - ./gradlew -u -i -S tomcatClearLogs
  # test HSQL
  - ./gradlew -u -i -S hsqlStart
  - ./gradlew -u -i -S dataInit
  - ./gradlew -u -i -S hsqlStop

cache:
  directories:
    - .gradle
    - $HOME/.gradle/
