language: java

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      jdk: oraclejdk8
    - os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
    - os: osx
      osx_image: xcode9.1 # OSX 10.12, Oracle Java 8

script:
  # test embedded tomcat
  - ./gradlew -u -i -S tomcatInstall
  - ./gradlew -u -i -S tomcatStart
  - ./gradlew -u -i -S tomcatStop
  - ./gradlew -u -i -S tomcatClearLogs
  # test HSQL
  - ./gradlew -u -i -S hsqlStart
  - ./gradlew -u -i -S dataInit
  - ./gradlew -u -i -S hsqlStop
  # test skin generation tool
  - ./gradlew -u -i -S skinGenerate -DskinName=travis

cache:
  directories:
    - .gradle
    - $HOME/.gradle/
